Repository emsuryadi/Chaakksss, pull requests merged in 2020-10, with the labels that each got.

#1 Application
  .gitignore
  README.md
  app.py
  data/.dummy
  requirements.txt
  run.py
  static/main.css
  static/overlay.png
  templates/index.html
  tools.py
Labels: hacktoberfest-accepted

#2 edit landing page information
  templates/index.html
Labels: hacktoberfest-accepted

#4 fix typo
  templates/index.html
Labels: bug, hacktoberfest-accepted

#3 Add favicon to index.html
  static/icon.ico
  templates/index.html
Labels: enhancement, hacktoberfest-accepted

#5 edit information
  README.md
  templates/index.html
Labels: enhancement, hacktoberfest-accepted

#7 update separator
  tools.py
Labels: enhancement
